Cargo.toml, README.md, examples/components/src/main.rs, examples/counter/src/main.rs, examples/hello/Cargo.toml, examples/hello/index.html, examples/hello/src/main.rs, maple-core-macro/src/attributes.rs, maple-core-macro/src/element.rs, maple-core-macro/src/lib.rs, maple-core-macro/tests/ui/component-fail.stderr, maple-core-macro/tests/ui/element-fail.rs, maple-core-macro/tests/ui/element-fail.stderr, maple-core-macro/tests/ui/element-pass.rs, maple-core/Cargo.toml, maple-core/src/internal.rs, maple-core/src/lib.rs
Callbacks now accept a parameter of type `Event`.
Part 2 will make the event the appropriate type (e.g. `MouseEvent`, `InputEvent` etc...), depending on the event name.
Closes #12
=> Receive Event in callback (Part 1)

maple-core/src/reactive.rs
`Computation` previously had two boxes (or well box-likes) as it was essentially an `Rc<Box<dyn Fn()>>` - so I replaced this with just an `Rc<dyn Fn()>`. Additionally, I switched from a `Vec<Rc<Computation>>` to a `HashSet<Computation>`, which should allow `observe` to become a constant-time instead of linear-time operation.
=> Remove double-boxing of Computation

.github/workflows/build_docs.yml, .github/workflows/rust.yml, maple-core/src/reactive.rs
=> Refactor effect dependency tracking

README.md, examples/components/src/main.rs, examples/counter/src/main.rs, examples/hello/src/main.rs, maple-core/src/lib.rs, maple-core/src/macros.rs, maple-core/src/reactive.rs
The cloned! macro clones all its arguments and than inlines the expression at the end.
=> Add cloned! macro

.github/workflows/rust.yml, maple-core-macro/src/children.rs, maple-core/src/internal.rs, maple-core/src/reactive/effect.rs
Clippy is a useful tool for preventing common mistakes. One mistake it caught in the existing code is that we were comparing `*const dyn Fn`s. This compares the vtable pointer as well as the data pointer, but comparing the vtable pointer is entirely meaningless and could cause bugs, so I changed it to just compare the data pointer.
=> Use Clippy

README.md, docs/src/header.rs, docs/src/usage.rs, examples/components/src/main.rs, examples/counter/src/main.rs, examples/hello/src/main.rs, maple-core-macro/src/children.rs, maple-core-macro/src/element.rs, maple-core-macro/src/lib.rs, maple-core-macro/src/text.rs, maple-core-macro/tests/ui/element-fail.stderr, maple-core/src/internal.rs, maple-core/src/lib.rs, maple-core/src/reactive/effect.rs, maple-core/src/reactive/signal.rs, maple-core/src/render.rs
=> Nested templates

maple-core/src/lib.rs, maple-core/src/reactive.rs, maple-core/src/reactive/effect.rs
Fixes #21 
Adds support for the `on_cleanup` hook. `on_cleanup` is tied to the reactive scope. When the reactive scope (aka `Owner`) is dropped, all the cleanup callbacks are called. Components are created in a new reactive scope so calling `on_cleanup` inside a component will trigger the callback when the component is destroyed.
=> Component lifecycle

examples/todomvc/Cargo.toml, examples/todomvc/index.html, examples/todomvc/src/copyright.rs, examples/todomvc/src/footer.rs, examples/todomvc/src/header.rs, examples/todomvc/src/item.rs, examples/todomvc/src/list.rs, examples/todomvc/src/main.rs, maple-core-macro/src/component.rs, maple-core-macro/src/lib.rs, maple-core-macro/tests/ui/component-fail.stderr, maple-core/Cargo.toml, maple-core/src/flow.rs, maple-core/src/lib.rs, maple-core/src/reactive/effect.rs, maple-core/src/reactive/signal.rs, maple-core/tests/integration.rs
This PR also includes some bug fixes and QOL improvements discovered while implementing TodoMVC:
- Implement `std::fmt::Debug` for `Signal` and `StateHandle`
- Parse keywords in component path
- Fix parsing of a component followed immediately by an interpolated value
The following code previously failed to parse:
```rust
template! {
div {
MyComponent()
(interpolated_value)
}
}
```
because the interpolated value would be treated as a function call of the previous component.
- Add an `untrack` utility for creating an untracked scope. This is useful when for example, calling a passed in closure and not wanting it to subscribe to current reactive scope.
- Create components inside an `untrack`ed scope (fixes tracking bugs when using `template!` inside interpolated values).
- Implement …
=> Complete TodoMVC spec conforming implementation

maple-core/src/easing.rs
Functions for circular, sine, exponential and bouncing easing have been added to `easing.rs`. Further, I added 3 constants. This doesn't have to close (#88), since one could still add functions.
- I took most functions from [https://easings.net/](here), yet had no idea yet how to test the functions.
- A few things about the bouncing easing could be added improved:
-  One could clarify the choice of numbers
- Some of the code could be more compact and more configurable.
=> Add specified easing functions specified in (#88)

docs/src/header.rs, docs/src/index.rs, docs/src/sidebar.rs, packages/sycamore-router/Cargo.toml, packages/sycamore-router/src/router.rs, packages/sycamore/src/generic_node/dom_node.rs
=> Router use anchor tags

docs/index.css, docs/markdown/basics/reactivity.md, docs/package-lock.json, docs/package.json, docs/src/content.rs, docs/src/header.rs, docs/src/index.rs, docs/src/main.rs, docs/tailwind.config.js, packages/sycamore-router/src/router.rs
- Extract outline from markdown and display in outline viewer
- Updated index page
=> Website improvements

packages/sycamore-router/Cargo.toml, packages/sycamore-router/src/router.rs
This PR should close https://github.com/sycamore-rs/sycamore/issues/129.
I'm not 100% sure of the logic, because in the SvelteKit router code that was referenced in the issue (https://github.com/sveltejs/kit/blob/8854e2ffc48cf653854828f6ac19b2ce620535a6/packages/kit/src/runtime/client/router.js#L103), the key presses were checked immediately and if found the function immediately returned. So, in the code below, I skipped all of the subsequent logic if any of those keys were pressed. I'm not sure if the behavior is that we expect only the ```prevent_default``` from happening (in which case, I can update those two sections separately).
=> Router should not prevent default if meta keys are held down

packages/sycamore-router/src/router.rs, website/src/content.rs
=> Add tests for StaticRouter

packages/sycamore/Cargo.toml
In some environments, indexmap's detection of the std crate fails, causing sycamore builds to fail (IndexSet has a variable number of type arguments depending on this detection).
This pull request sets indexmap's std feature flag explicitly, negating the need for automatic detection.
See also:
* [indexmap issue](https://github.com/bluss/indexmap/issues/184)
* [similar issue in google/cargo-raze](https://github.com/google/cargo-raze/issues/114)
* [indexmap's has_std causing issues with intellij](https://github.com/intellij-rust/intellij-rust/issues/4631)
=> Explicitly enable std feature for indexmap

packages/sycamore/src/utils/render.rs
I noticed when using the `Keyed` component that when the `KeyedProps::iterable`
value changed from a large `Vec` to a smaller one containing a subset of the
original, not all the obsolete nodes were removed from the DOM.
Specifically, I started with a `Vec` with 10 elements, then removed all but the
third one.  The nodes before the remaining node were removed, but not the ones
after it.  This patch fixes the problem.
=> fix logic error in `reconcile_fragments`

docs/build.rs, docs/next/advanced/routing.md, packages/sycamore-router/src/router.rs, packages/sycamore/src/generic_node.rs, packages/sycamore/tests/ssr/main.rs, website/src/main.rs
Closes #123 
This PR introduces the new `Integration` trait that abstracts over the browser's History API.
This also introduces `HistoryIntegration` and `StaticIntegration` for client-side and server-side routing respectively.
=> Router integrations

.github/workflows/bench.yml, .github/workflows/build_website.yml, .github/workflows/build_website_prod.yml, .github/workflows/continuous_bench.yml, .github/workflows/js_framework_bench.yml, .github/workflows/test.yml, docs/build.rs, docs/next/basics/template.md, packages/sycamore-macro/src/template/attributes.rs, packages/sycamore-macro/src/template/element.rs, packages/sycamore-macro/tests/template/component-fail.stderr, packages/sycamore-macro/tests/template/element-fail.rs, packages/sycamore-macro/tests/template/element-fail.stderr, packages/sycamore-macro/tests/template/element-pass.rs, packages/sycamore-macro/tests/template/root-pass.rs, packages/sycamore-router-macro/tests/router/router-fail.stderr, packages/sycamore-router/src/lib.rs, packages/sycamore/src/generic_node.rs, packages/sycamore/src/generic_node/dom_node.rs, packages/sycamore/src/generic_node/ssr_node.rs, packages/sycamore/src/utils/render.rs, website/index.css, website/src/content.rs
=> Implement dangerously_set_inner_html

website/src/index.rs
was going to: `https://sycamore-rs.netlify.app/basics/reactivity` with a `404`
=> fix broken link to reactivity doc on main page

docs/versioned_docs/v0.5/getting_started/hello_world.md
Hi! Just exploring Sycamore (looks cool so far) and ran into trouble running the hello world example, which doesn't describe creating index.html, which Trunk needs. Following the current instructions gives an error:
```
$ trunk serve                        
Error: error getting canonical path to source HTML file "index.html"
Caused by:
No such file or directory (os error 2)
```
So I thought I'd fix that :)
The page in question also previously said:
> In fact, the Hello World program in Sycamore is but slightly longer than the console version!
But the console version is not described. So I've removed this sentence.
Finally, the description of the sycamore repo on Github is
> A reactive DOM library for Rust in WASM 
I only mention this in case you wanted to update it to "Sycamore is a …
=> Explain that Trunk needs a HTML source file

.gitignore, .vscode/settings.json, docs/next/advanced/advanced_reactivity.md, docs/next/contribute/architecture.md, examples/context/src/main.rs, packages/sycamore-macro/src/lib.rs, packages/sycamore-macro/src/template/attributes.rs, packages/sycamore-macro/src/template/component.rs, packages/sycamore-reactive/src/effect.rs, packages/sycamore-reactive/src/signal.rs, packages/sycamore-router/src/router.rs, packages/sycamore/benches/reactivity.rs, packages/sycamore/src/context.rs, packages/sycamore/src/flow.rs, packages/sycamore/src/generic_node/dom_node.rs, packages/sycamore/src/generic_node/ssr_node.rs, packages/sycamore/src/lib.rs, packages/sycamore/src/motion.rs, packages/sycamore/src/template.rs, packages/sycamore/src/utils/render.rs
`rx` is ambiguous with ReactiveX-family of libraries: http://reactivex.io/
=> Rename rx to reactive

packages/sycamore/src/generic_node/ssr_node.rs, packages/sycamore/tests/ssr/main.rs
`remove_child` used to remove all nodes instead of only the specified node.
Added some regression tests.
=> Fix SsrNode remove_child

docs/build.rs, website/Cargo.toml, website/index.css, website/package-lock.json, website/package.json, website/postcss.config.js, website/src/header.rs, website/src/index.rs, website/src/main.rs, website/src/news_index.rs, website/src/sidebar.rs, website/src/versions.rs, website/tailwind.config.js
=> Website dark mode

packages/sycamore-reactive/src/effect.rs
Alternative to `Signal::new`, uses a reducer function to get next value
=> `create_reducer`

packages/sycamore-reactive/src/effect.rs, packages/sycamore-router-macro/Cargo.toml, packages/sycamore-router-macro/src/parser.rs, packages/sycamore-router-macro/src/route.rs, packages/sycamore-router-macro/tests/router/router-fail.stderr, packages/sycamore-router/src/lib.rs, website/src/index.rs
=> Fix router parser not parsing identifiers

docs/next/advanced/routing.md, packages/sycamore-router/src/router.rs, website/src/versions.rs
Adding `rel="external"` to an anchor element (`<a>`) will prevent the router from intercepting the click and let the browser perform the default navigation behavior.
This is useful when there are other pages that are hosted on the same origin but are not managed by the router.
=> Do not intercept anchors with `rel="external"`

docs/next/basics/template.md, docs/versioned_docs/v0.5/basics/template.md, docs/versioned_docs/v0.6/basics/template.md
Going through [docs](https://sycamore-rs.netlify.app/docs/basics/template#attributes) came across this 
and Rust compiler complained, hence this update.
=> Update docs to use boolean for disabled attribute on button

packages/sycamore/src/utils/render.rs, packages/sycamore/tests/web/main.rs
=> Properly handle dynamic nodes in a fragment

docs/versioned_docs/v0.6/basics/reactivity.md
=> Added docs on topological dependency tracking

packages/sycamore-reactive/src/signal.rs
=> impl Default for Signal<T: Default>

packages/sycamore/src/generic_node.rs, packages/sycamore/src/generic_node/dom_node.rs, packages/sycamore/src/generic_node/ssr_node.rs
This is useful to have, especially for some serializers which require certain properties to not exist, not just be `undefined`.
=> Added `remove_property` method to `GenericNode`

packages/sycamore-macro/src/lib.rs, packages/sycamore-macro/src/template/mod.rs, packages/sycamore/src/lib.rs
This macro works well for cases where we need access to underlying `GenericNode` operations, such as `.event()`, `.add_attribute()`, `.remove_attribute` that cannot currently be performed inside of the `template!` macro, yet retain the ergonomics for setting attributes and children that don't need the extra flexibility. Please see the `doc example` below for a possible use case.
This is also a good workaround for #264.
=> Added node! convenience macro

examples/todomvc/src/filter.rs, examples/todomvc/src/footer.rs, examples/todomvc/src/header.rs, examples/todomvc/src/item.rs, examples/todomvc/src/list.rs, examples/todomvc/src/main.rs
Does what it says on the tin, and it's so beautiful 😭
Closes https://github.com/sycamore-rs/sycamore/issues/279
=> Update TodoMVC example to use Context API

packages/sycamore-macro/src/component/mod.rs, packages/sycamore-macro/src/template/component.rs, packages/sycamore-macro/tests/template/component-fail.rs, packages/sycamore-macro/tests/template/component-pass.rs, packages/sycamore/src/builder/agnostic/mod.rs, packages/sycamore/src/generic_node.rs, packages/sycamore/src/generic_node/dom_node.rs, packages/sycamore/src/generic_node/ssr_node.rs, packages/sycamore/src/lib.rs, packages/sycamore/src/portal.rs, website/src/main.rs
This fixes the ugly hack of using
```rust
if TypeId::of::<G>() == TypeId::of::<DomNode>() { ... }
```
and replaces it with
```rust
if G::IS_BROWSER { ... }
```
=> Add `IS_BROWSER` constant to `GenericNode`

packages/sycamore/Cargo.toml, packages/sycamore/src/futures.rs, packages/sycamore/src/lib.rs, packages/sycamore/src/portal.rs
The `wasm-bindgen-interning` feature in turn enables the `wasm-bindgen/enable-interning` feature.
This feature is on by default.
=> Make `wasm-bindgen-interning` a feature

packages/sycamore-router/src/router.rs, packages/sycamore/src/builder/agnostic/mod.rs, packages/sycamore/src/generic_node.rs, packages/sycamore/src/generic_node/dom_node.rs, packages/sycamore/src/generic_node/ssr_node.rs, packages/sycamore/src/portal.rs
This allows creating rendering backends that do not use `web_sys::Event` in event handlers
=> Make `GenericNode` generic over the event type

docs/next/advanced/routing.md, docs/next/basics/components.md, examples/components/src/main.rs, packages/sycamore-reactive/src/effect.rs, packages/sycamore-reactive/src/iter.rs, packages/sycamore-reactive/src/signal.rs, packages/sycamore-router/src/router.rs, packages/sycamore/src/builder/agnostic/mod.rs, packages/sycamore/src/flow.rs, packages/sycamore/src/lib.rs, packages/sycamore/src/view.rs, website/src/main.rs
=> Rename `StateHandle` to `ReadSignal`

packages/sycamore-macro/src/view/attributes.rs
=> Autocomplete should not be boolean attribute

packages/sycamore/src/generic_node/dom_node.rs, packages/sycamore/src/lib.rs
As I mentioned in https://discord.com/channels/820400041332179004/821489793258487839/912364912624418846 I was having problems with things not getting dropped when gradually converting an existing app to use sycamore.
This function is intended to be used for injecting an ephemeral sycamore view into a non-sycamore app
(for example, a file upload modal where you want to cancel the upload if the modal is closed).
You should only use this function while refactoring your app, and you should aim to have a single
call to [`render`] or [`render_to`] at the top level of your app long-term.
Using this function did solve my problems.
=> render_temporarily_to() helper

packages/sycamore-macro/Cargo.toml, packages/sycamore-macro/src/view/element.rs, packages/sycamore-macro/tests/view/element-pass.rs
Fixes #262 
Adds an extra `(...)` around `#splice` in `packages/sycamore-macro/src/view/element.rs` to make sure whole expression is borrowed.
=> Fix parenthesizing of expressions in `view!` interpolation syntax

packages/sycamore-reactive/src/context.rs
This makes it much easier to debug `"context not found for type"` errors.
=> Add `#[track_caller]` for `use_context`

packages/sycamore-reactive/src/context.rs, packages/sycamore-reactive/src/effect.rs, packages/sycamore-reactive/src/iter.rs, packages/sycamore-reactive/src/lib.rs, packages/sycamore/src/context.rs, packages/sycamore/src/futures.rs, packages/sycamore/src/view.rs
=> Fix contexts inside effects

packages/sycamore-macro/src/component/mod.rs
=> Filter phantom_generics to contain types only

packages/sycamore/src/utils/render.rs, packages/sycamore/tests/web/hydrate.rs
This fixes a bug where dynamic text nodes are the single child of parent would be inserted twice when hydrating on the client side.
Fixes #319
=> Hack to fix duplicate text when hydrating

packages/sycamore-macro/src/view/attributes.rs
It needs to be possible to disable spellcheck explicitly: `<textarea spellcheck="false">`: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/spellcheck
`translate` is actually a `yes` `no` property: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/translate
=> Fix spellcheck and translate attributes

website/index.css, website/src/content.rs, website/src/header.rs, website/src/index.rs, website/src/main.rs, website/src/sidebar.rs, website/tailwind.config.js
https://github.com/sycamore-rs/sycamore/issues/302  
sidebar & navbar are collapsed into the hamburger menu
side effects / fixes note:
* backdrop blurs now work in dark mode
* code blocks will scroll instead of wrapping if overflowed
* sidebar is pinned on desktop screen
* slightly increased blur radius for better text readability
* main text's max width is limited to around 900px
* slightly reduced the font size of sidebar
* added a small margin on index page
=> fix broken website on small screens

packages/sycamore-macro/src/view/codegen.rs, packages/sycamore-macro/tests/view/element-fail.rs, packages/sycamore-macro/tests/view/element-fail.stderr, packages/sycamore/src/component.rs, packages/sycamore/src/html/mod.rs, packages/sycamore/src/lib.rs, packages/sycamore/src/suspense.rs
=> Type-checking and IDE completions for HTML tags

packages/sycamore-macro/src/view/codegen.rs, packages/sycamore-macro/src/view/ir.rs, packages/sycamore-macro/src/view/mod.rs, packages/sycamore-reactive/src/context.rs, packages/sycamore/src/generic_node/ssr_node.rs, packages/sycamore/src/view.rs, packages/sycamore/tests/ssr/main.rs, website/Cargo.toml
If the identifier `ctx` is used inside a dynamic expression inside the `view!` macro, a new scoped effect will be automatically created instead. This prevents memory leaks when the effect reruns.
=> Create a new nested scope if `ctx` is used within a dyn fragment

Cargo.toml, examples/hello-builder/Cargo.toml, examples/hello-builder/index.html, examples/hello-builder/src/main.rs, packages/sycamore-macro/src/view/parse.rs
I have finally started work on the task of porting my code to sycamore 0.8, and thought I would give the builder api some love.
I have resurrected this example for selfish reasons as well (so that I have a template for writing up minimal reproduction cases, when I run into problems).
=> port builder example to 0.8

docs/next/basics/view.md, examples/README.md, examples/hello-builder/Cargo.toml, packages/sycamore/Cargo.toml, packages/sycamore/src/builder.rs, packages/sycamore/src/generic_node/hydrate_dom.rs, packages/sycamore/src/lib.rs, packages/sycamore/tests/web/builder_hydrate.rs, packages/sycamore/tests/web/hydrate.rs, packages/sycamore/tests/web/main.rs
=> Fix top-level dynamics nodes with hydration

packages/sycamore-reactive/src/arena.rs, packages/sycamore-router/src/router.rs, packages/sycamore/src/generic_node/dom_node.rs, packages/sycamore/src/generic_node/mod.rs, packages/sycamore/src/generic_node/ssr_node.rs, packages/sycamore/tests/web/main.rs
=> Clearlify specify behavior of GenericNode::add_class to split multiple classes at whitespace

packages/sycamore-macro/src/view/codegen.rs, packages/sycamore/src/builder.rs, packages/sycamore/src/generic_node/dom_node.rs, packages/sycamore/src/generic_node/hydrate_dom.rs, packages/sycamore/src/generic_node/mod.rs, packages/sycamore/src/generic_node/ssr_node.rs, packages/sycamore/src/html/mod.rs, packages/sycamore/src/noderef.rs, packages/sycamore/tests/web/main.rs, packages/sycamore/tests/web/reconcile.rs
=> Add support for SVG

packages/sycamore/src/generic_node/hydrate_dom.rs
Add more checks on client-side to ensure hydrated elements match.
=> More fault tolerant hydration

packages/sycamore-macro/src/view/codegen.rs, packages/sycamore/src/utils/mod.rs
Fixes exponential code generation when using SSR and hydration with the `view!` macro.
Also fixes hydration errors related to the fact that code in client side is not executed in the same order as on the server side.
=> Simplify SsrNode and HydrateNode codegen in view! macro

packages/sycamore-macro/src/view/codegen.rs, packages/sycamore-reactive/src/signal.rs, packages/sycamore/src/generic_node/dom_node.rs, packages/sycamore/src/generic_node/hydrate_dom.rs, packages/sycamore/src/generic_node/mod.rs, packages/sycamore/src/generic_node/ssr_node.rs
=> Implement AddAssign and friends for Signal

packages/sycamore-macro/src/view/codegen.rs, packages/sycamore-reactive/src/signal.rs, packages/sycamore/src/generic_node/dom_node.rs, packages/sycamore/tests/web/main.rs, packages/sycamore/tests/web/svg.rs
=> Support setting class on SVG elements

packages/sycamore-macro/src/view/parse.rs, packages/sycamore-macro/tests/view/component-pass.rs
Adds support for field init shorthand syntax, with tests.
```rust
let signal = create_signal(cx, 0);
view! { cx, Component { signal } }
```
=> Allow field init shorthand for component prop fields

.github/workflows/coverage.yml, packages/sycamore-macro/Cargo.toml, packages/sycamore-macro/src/component/mod.rs, packages/sycamore-macro/src/view/ir.rs, packages/sycamore-macro/src/view/parse.rs, packages/sycamore-macro/tests/component/component-fail.rs, packages/sycamore-macro/tests/component/component-fail.stderr, packages/sycamore-macro/tests/component/component-pass.rs, packages/sycamore-macro/tests/view/component-fail.rs, packages/sycamore-macro/tests/view/component-fail.stderr, packages/sycamore-macro/tests/view/component-pass.rs, packages/sycamore-macro/tests/view/element-fail.stderr
Notable changes:
- Fixes macro hygiene when using async components.
- Adds `#![no_implicit_prelude]` to certain UI tests.
- Improves `#[component]` macro diagnostic spans.
- Adds additional UI tests for `#[component]`.
- Include UI tests in coverage reports.
=> Fix some macro edge cases and improve macro hygiene/diagnostics

packages/sycamore-macro/src/view/parse.rs, packages/sycamore-macro/tests/view/component-pass.rs
The parsing logic for components in a view was missing a check for children using function-like calling.
Before this commit, the following snippet would compile:
```rust
view! { cx, Component { Child {} } }
view! { cx, Component { div {} } }
```
...while this would not:
```rust
view! { cx, Component { Child() } }
view! { cx, Component { div() } }
```
<br>
Tests are added to ensure that either way of calling a component compiles.
=> Handle parsing of component children with function-like syntax

Cargo.toml, examples/README.md, examples/http-request-builder/Cargo.toml, examples/http-request-builder/index.html, examples/http-request-builder/src/main.rs
This adds the same example as the `http-request` but using the builder
syntax.
Most of the code is the same and a fair degree of the change from macro
to builder syntax is trivial. Using `Suspense` with the builder syntax
does not seem to be covered in the documentation. This also shows off that structs
that derive `Prop` have public builders which may be required using the
builder syntax - such as with `SuspenseProps`.
I added a comment to the `SuspenseProps` part just because I don't think it is obvious
or documented (on the website) that by deriving `Prop` you get a free typed builder too :)
I know @lukechu10 spoke about changing the API around Suspense in the builder
syntax on Discord - so I'm aware you might have reason to not accept this PR yet (or at all) if
those changes are …
=> Add the http-request-builder example

packages/sycamore-macro/src/component/mod.rs, packages/sycamore-macro/tests/view/component-pass.rs
Fixes #410
This PR fixes support in the `#[component]` macro for destructured struct patterns of props.
I added a single test to trybuild using the existing prop struct with generics and lifetimes to show it handles those too :)
I started trying to do what I think was [discussed here](https://github.com/sycamore-rs/sycamore/issues/410#issuecomment-1101893839) only to find that trying to match on fields that themselves might also be destructured was a rabbit hole I didn't want to go down :)
So instead this change simply alters the new sync function that we create to wrap around the async one - it takes the type from the destructured pattern and converts it into a `syn::PatType` (i.e. `props: MyProps`) then we just have to add this ident to the args we supply the async function and the …
=> Fix destructuring async props

examples/http-request-builder/src/main.rs, packages/sycamore/src/html/mod.rs
This just lets users use the `body` element. I'm not at all familiar with this part of the codebase, so please let me know if there's anything else I need to do to make this work.
Once this is merged, a new beta release would be greatly appreciated so that Perseus can take advantage of this as soon as possible!
=> Add support for `body`

packages/sycamore-reactive/src/effect.rs, packages/sycamore-web/src/dom_node.rs
Also simplifies the implementation for `DomNode::event`.
=> Use create_ref instead of on_cleanup for allocating event handlers

packages/sycamore-reactive/Cargo.toml, packages/sycamore-reactive/src/arena.rs, packages/sycamore-reactive/src/effect.rs, packages/sycamore-reactive/src/iter.rs, packages/sycamore-reactive/src/lib.rs, packages/sycamore-reactive/src/memo.rs, packages/sycamore-reactive/src/signal.rs, packages/sycamore-web/src/dom_node.rs
Optimizations in `sycamore-reactive` crate.
Some notable changes:
- Simplify and reduce allocations in `map_keyed` and `map_indexed`.
- Make `Signal::trigger_subscribers` slightly faster.
=> Some performance tweaks

docs/next/basics/view.md
The `builder` feature flag was removed in #416 but the website still
contained a sentence about adding the feature flag before using the
builder syntax.
=> Remove `builder` feature doc on website

packages/sycamore-reactive/src/context.rs
Hi 👋,
Just a quick fix so that the `scope_depth` function returns `0` for the root scope as stated by the comment - 
I also added some tests for the function too.
This function is only ever used in this repository for the following SSR test: https://github.com/sycamore-rs/sycamore/blob/487877f2aee232b4a04c0dd6589a3b2240d292d3/packages/sycamore/tests/ssr/main.rs#L120-L136 
that relies solely on the fact that depth is incremented on child scopes.
=> Fix `scope_depth` to return 0 for root scope

packages/sycamore-core/src/render.rs
Fixes #427 
The #427 bug was introduced in #416 inside the `reconcile_fragments` function.
The quick fix was to add the negation that got dropped during that change - this seems
to have caused the bug.
~I instead extracted the removal of nodes from the parent node part of the 
`reconcile_fragments` function to a new function and added tests for this new 
function to avoid any future regressions.~
~The tests use a pretty rough/bare bones mock of a `GenericNode` in order to satisfy the
trait bounds required by the extracted function. I think the tests are worth the added file
noise of the mock but let me know if you'd prefer I remove it (and probably the extracted
function at that point).~
=> Fix removing old nodes from parent

examples/hello-builder/src/main.rs, examples/higher-order-components/src/main.rs, examples/http-request-builder/src/main.rs, packages/sycamore-core/src/component.rs, packages/sycamore-macro/src/component/mod.rs, packages/sycamore-macro/src/view/codegen.rs, packages/sycamore-macro/tests/view/component-fail.stderr, packages/sycamore/src/builder.rs
Removes the default `()` unit property when no properties are
specified in the Component definition.
Removes the above assumption in the `view` macro codegen.
Removes the `UnitBuilder` struct and Unit prop impl from `sycamore-core`.
Fixes #415
=> Fix default Unit property on Component

packages/sycamore-web/src/lib.rs
Adds a new function in `sycamore-web` that creates a 
`GenericNode` from a `web_sys::Element` and depending 
on the type will reuse the element in the DOM.
This approach tries to cover the concern of [recreating
existing node](https://github.com/sycamore-rs/sycamore/issues/261#issuecomment-925476447) and returning a `G: GenericNode` that can be used easily.
The function accepts `web_sys::Element` instead of
`web_sys::Node` to avoid having to do error checking
for the case of some non element node. If the user
is using this function then they are probably already
in the know about how to use `JsCast` to get this type
and they can deal with whether they need the overhead
of type checking (in js land anyway).
Not a big fan of the unsafe transmutes in general but 
going the `&dyn Any` …
=> Add a generic `from_web_sys` function

docs/next/basics/view.md, examples/motion/src/main.rs, examples/todomvc/src/main.rs, packages/sycamore-macro/src/view/codegen.rs, packages/sycamore-macro/src/view/ir.rs, packages/sycamore-macro/src/view/parse.rs, packages/sycamore-macro/tests/view/element-fail.rs, packages/sycamore-macro/tests/view/element-fail.stderr, packages/sycamore/tests/web/main.rs
Adds the ability to set properties directly in the view macro that
accepts any value that can be converted into the `JsValue`.
Supports both static and dynamic values in a similar manner that
attributes do currently.
Updates some of the examples to use the new directive when the type can
be used directly as a property instead of cloning or serializing the
value.
I did update the website to include a section on this new directive but there
is not a similar section for the builder API, so I'm not sure if you want to keep
this out or whether you'd like me to add something similar for the builder docs :).
Closes #330
=> Add the `prop:*` directive to the view macro

packages/sycamore-reactive/src/signal.rs
Exposes `trigger_subscribers` function from `SignalEmitter` to `Signal`'s public interface.
=> Add `trigger_subscribers` to `Signal`

packages/sycamore-router-macro/src/route.rs, packages/sycamore-router/src/lib.rs, packages/sycamore-router/src/router.rs
This solves a problem I had with Sycamore last year: that `Route` can only be an `enum`, meaning additional custom information can't be easily attached to the router system. Perseus required this, and did a very hacky workaround that both reduced routing performance there and made for some really weird semantics. With arctic-hen7/perseus#151 though, that workaround it no longer feasible, so this makes `Route` be able to be a `struct`, and `match_route` now takes `&self`.
To achieve this, I've broken out the `Router` into a `Router` and a `RouterBase`, with the former being a wrapper around the latter that simply calls it with `R::default()`, which is now derived automatically in `enum`s as the `#[not_found]` route. All tests pass, and I'm pretty sure I've covered everything, but a review …
=> Add support for `struct` `Route`s

packages/sycamore-router/src/router.rs
Missing debug after #441 added by #434.
I noticed this because the website failed to build.
=> Add debug impl for RouterBaseProps

packages/sycamore/tests/web/builder_hydrate.rs, packages/sycamore/tests/web/hydrate.rs, packages/sycamore/tests/web/indexed.rs, packages/sycamore/tests/web/keyed.rs, packages/sycamore/tests/web/main.rs, packages/sycamore/tests/web/reconcile.rs, packages/sycamore/tests/web/render.rs, packages/sycamore/tests/web/svg.rs, packages/sycamore/tests/web/utils.rs
Hi 👋,
This PR does five things for the tests in `packages/sycamore/tests/web/`. 
1. Add `query` utility function to replace `{document}.query_selector({selectors}).unwrap().unwrap()`
2. Add `query_into` utility function to replace `{document}.query_selector({selectors}).unwrap().unwrap().unchecked_into::<{element_type}>()`
3. Add a new `assert_text_content` macro, which is similar to `assert_eq` but it will call `Node::text_content` and `unwrap` the value for the `left` expression before passing it to `assert_eq`.
4. Uses the methods available in `HtmlInputElement` for getting and setting the `value` property instead of using the `Reflect` methods.
5. I noticed the svg test which didn't assert that the class was added correctly, so I thought I'd add the assertion for this :)
Hopefully you …
=> Refactor web tests

examples/components/src/main.rs, examples/context/src/main.rs, examples/hello-world/src/main.rs, examples/http-request/src/main.rs, examples/iteration/src/main.rs, examples/js-framework-benchmark/src/main.rs, examples/ssr/src/main.rs, examples/svg/src/main.rs, examples/todomvc/src/main.rs, examples/transitions/src/main.rs, packages/sycamore-macro/src/view/codegen.rs, packages/sycamore-macro/src/view/ir.rs, packages/sycamore-macro/src/view/parse.rs, packages/sycamore-macro/tests/view/component-fail.rs, packages/sycamore-macro/tests/view/component-fail.stderr, packages/sycamore-macro/tests/view/component-pass.rs, packages/sycamore-macro/tests/view/element-fail.rs, packages/sycamore-macro/tests/view/element-fail.stderr, packages/sycamore-router/src/router.rs, packages/sycamore/benches/ssr.rs, packages/sycamore/src/suspense.rs, packages/sycamore/tests/ssr/main.rs, packages/sycamore/tests/web/indexed.rs, packages/sycamore/tests/web/keyed.rs, packages/sycamore/tests/web/portal.rs, website/src/content.rs, website/src/main.rs
=> Parse new view syntax

.github/workflows/test.yml, docs/next/getting_started/installation.md, examples/transitions/src/main.rs, packages/sycamore-core/src/component.rs, packages/sycamore-core/src/view.rs, packages/sycamore-macro/src/view/mod.rs, packages/sycamore-macro/src/view/parse.rs, packages/sycamore-macro/tests/view/component-fail.stderr, packages/sycamore-reactive/src/effect.rs, packages/sycamore-reactive/src/iter.rs, packages/sycamore-reactive/src/lib.rs, packages/sycamore-web/src/ssr_node.rs, website/src/main.rs
A lot of `unsafe` code was removed from `sycamore-reactive` and `sycamore-core` with the new "NLL" feature stabilized in Rust 1.63.0
Also removes `Children::call_with_bounded_scope` since it is exactly the same as `Children::call`.
=> Update MSRV to 1.63.0 and remove some unsafes

packages/sycamore-core/src/generic_node.rs, packages/sycamore-router/src/router.rs
Previously, `Router` would panic if the children was node a single node. This meant that fragments and dynamic views had to be wrapped by another node (often a `<div>` or a `<main>`). This PR removes this restriction.
=> Allow fragments and dynamic views in `RouterBase`

packages/sycamore/src/builder.rs
In https://github.com/rust-lang/rust/pull/95474#issuecomment-1228705007 we are attempting to deploy a soundness bug fix for rare cases of `impl Trait` causing UB. While your crate does not use this unsoundly, it requires an additional annotation in order for rustc to be able to figure out that your case is actually sound.
This change was done by following the [diagnostics emitted by the rustc that contains the bugfix](https://crater-reports.s3.amazonaws.com/pr-95474-1/try%23d47ae2a6ecee02f32f23667fe1152f9a71e39e8c/reg/perseus-0.4.0-beta.7/log.txt).
=> Forward compatibility fix for breakage due to a soundness fix in rustc

packages/sycamore-core/src/lib.rs, packages/sycamore-core/src/stable_id.rs, packages/sycamore/src/lib.rs
This adds a way to generate IDs that are stable across the hydration boundary. If a hydration context is not available, it will fall back to a globally incremented ID.
This is useful for generating ids for accessible components and similar uses that require a stable globally unique ID.
```rust
let (component_id, id) = create_unique_id();
view! { cx,
div(aria-labelledby = format!("{}_{id}", component_id.unwrap_or_default())) {
// children
}
}
```
The format boilerplate would likely be abstracted into a custom hook specific to the application, this just provides the primitive so the IDs are guaranteed to be globally unique.
=> Add unique ID generation hook

packages/sycamore-macro/src/view/codegen.rs
When various `Signal` types are nested inside other structs, I wasn't able to use `bind:value` (the compiler would complain about `expected pattern` or something to that effect). I changed the proc macro codegen to fix it, and now this pattern works:
```rust
struct ThingRx {
name: RcSignal<String>,
}
// ...
view!{cx,
input(bind:value=c.name)
}
```
=> fixes bind macro problem

packages/sycamore-web/src/hydrate_node.rs
=> API docs correction for Functions hydrate_to: "use hydrate_to" can now read and link as "use hydrate".

packages/sycamore-core/src/render.rs, packages/sycamore/tests/web/render.rs
This fixes the panic described in #572.
It removes the loop that unwraps inner dynamic views from the render code for `ViewType::Dyn`. I don't understand its purpose in the first place, no tests failed after removing it, TodoMVC still works exactly as expected and even my contrived example to specifically trigger that loop renders and updates perfectly fine. So I can only assume it was extraneous code left over from a refactor.
=> Fix Issue #572

packages/sycamore-reactive/src/signal.rs
Adds `create_signal_unsafe`, the equivalent of `create_ref_unsafe`.
=> Add signal equivalent of `create_ref_unsafe`

packages/sycamore/src/builder.rs
See the comment added to builder.rs for the juicy details, but the tl;dr is that by *not* calling a shared internal function in the various `ElementBuilder` entrypoints, we avoid an exponential explosion in the size of the resulting Builder object type and thereby dodge limits on mangled symbol size.
An alternative solution would be recommending using `v0` name mangling (`RUSTFLAGS=-Csymbol-mangling-version=v0`) but that seems less convenient for users and anyway we should probably avoid generating exponential types in case the compiler takes a peek and gets very sad and slow.
This is kind of hard to add an automatic (stress) test for, as testing requires poking the generated `.wasm` file to see if any of the mangled names are looking exponential-ish.
=> Avoid exponential blowup in size of Builder type

packages/sycamore/src/builder.rs
=> Fix builder `bind_value` and `bind_checked` calling wasm functions in SSR

packages/sycamore-router/src/lib.rs, packages/sycamore-router/src/router.rs, website/index.css, website/package-lock.json
Continuation of #575 with fix for hash params.
This PR fixes route matching when the pathname includes a hash at the end.
This PR also fixes navigating to an anchor within the same page.
Finally, also enabled CSS `scroll-behavior: smooth` for nicer scrolling animation.
This means navigating to section links works again on the docs website!
=> Fix navigating to an anchor and route matching with hash parameters

packages/sycamore-macro/src/view/parse.rs, packages/sycamore-macro/tests/view/element-pass.rs
Switches `view!` AttributeName parser to `Ident::parse_any` to handle keywords in extended attribute names.
fixes #620 
```rs
view! { cx, p(class="my-class", data-ref-me="my-value") }
```
Prior to change, this would throw with
```
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
error: expected identifier, found keyword `ref`
--> tests/view/element-pass.rs:26:63
|
26 |         let _: View<G> = view! { cx, p(class="my-class", data-ref-me="my-value") };
|                                                               ^^^
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
```
=> fix view! parser to handle dashed attributes with Rust keywords (#620)

docs/next/advanced/optimize_wasm_size.md
`wee-alloc` should no longer be recommended because of a memory leak: https://github.com/rustwasm/wee_alloc/issues/85
It appears that the project is abandoned and that this issue will not be fixed anytime soon.
Fixes #614
=> Dont suggest wee-alloc in docs

packages/sycamore-reactive/src/effects.rs, packages/sycamore-reactive/src/root.rs
Also simplifies effects by simply making them into memos that have a value of `()`.
Follow-up to #626 
Supersedes #601
=> Make batch affect both memos and effects

examples/todomvc/src/main.rs, packages/sycamore-core/src/view.rs, packages/sycamore-reactive/src/iter.rs, packages/sycamore-reactive/src/memos.rs, packages/sycamore-reactive/src/signals.rs, packages/sycamore-reactive/src/utils.rs, packages/sycamore-router/src/router.rs, packages/tools/bench/benches/reactivity.rs
`Memo` used to be a wrapper struct around `ReadSignal` which did not provide anything extra so this makes everything simpler.
Follow-up to #626
=> Repace the `Memo` struct with `ReadSignal`

packages/sycamore-core/src/render.rs
This is a bit of a hack right now. The right way to do it would be to ensure that `current` only includes nodes that are children of `parent` as a pre-condition of the function.
This temporarily fixes website navigation in debug mode.
=> Fix panic about current not being a child of parent in clean_children

examples/js-framework-benchmark/Cargo.toml, examples/todomvc/Cargo.toml, packages/sycamore-web/src/lib.rs
Supersedes #568 
This adds a re-export in `sycamore-web` of `wasm-bindgen`, `js-sys`, and _only_ the event types from `web-sys` which are used from within Sycamore.
The reason why we don't re-export the entirety of `web-sys` is because all of the APIs are behind feature flags so it is very likely that the downstream user of Sycamore will need to add `web-sys` as a dependency anyways.
=> Re-export `wasm-bindgen`, `js-sys`, and event types from `web-sys`

packages/sycamore-core/src/component.rs, packages/sycamore-core/src/event.rs, packages/sycamore-core/src/generic_node.rs, packages/sycamore-core/src/lib.rs, packages/sycamore-core/src/stable_id.rs, packages/sycamore-futures/src/lib.rs, packages/sycamore-macro/src/lib.rs, packages/sycamore-reactive/src/effects.rs, packages/sycamore-reactive/src/lib.rs, packages/sycamore-reactive/src/node.rs, packages/sycamore-reactive/src/signals.rs, packages/sycamore-reactive/src/utils.rs, packages/sycamore-router-macro/src/lib.rs, packages/sycamore-web/src/lib.rs
This adds the `warn(missing_docs)` lint for all the crates and also adds more doctests for reactive signals.
=> Add missing docs and more doctests

examples/hydrate/index.html, examples/hydrate/src/main.rs, examples/hydrate/template.html
This changes the hydrate app to render the HTML when using `cargo run` so that we no longer need to manually update the HTML.
Closes #656
=> Improve generation of HTML for the hydrate example.

website/src/main.rs
#648
I might fix the bug.
`view!{}` was drawn two times when calling the code `if let Some(cached_sidebar_data) = cached_sidebar_data.get_clone(){view!{...}}`.
I think that the bug is around `cached_sidebar_data`.
For the reason, instead of calling from `fetch_docs_data`, I changed to `cached_sidebar_data` is initialized only once.
=> Fix creating <div> twice on website

.github/workflows/test.yml, CONTRIBUTING.md, docs/next/getting_started/installation.md, packages/sycamore-web/src/ssr_node.rs
Updates the MSVC to 1.73.0 because of `bumpalo`.
=> Update MSVC to 1.73.0

.github/workflows/build_website.yml, .github/workflows/js_framework_bench.yml, examples/hydrate/Trunk.toml
Fixes #662 
This PR updates Trunk to v0.19.1 which supports minification of assets. This however breaks the `hydrate` example which relies on hydration markers in the produced HTML file that are removed by minification. To fix this, we disable minification in `examples/hydrate/Trunk.toml`.
=> Update trunk to v0.19.1 and disable minification for hydrate example

packages/sycamore-reactive/src/context.rs
This let's us get the line and col info of the panic at the call site rather than in library code.
=> Add `track_caller` attribute to `provide_context*` and `use_context` functions

packages/sycamore-web/src/lib.rs
Allows to use `SubmitEvent` type explicitly in closures to fix error when submitting form with `on:submit`.
Currently the following code:
```rust
let submit_fn = move |e: Event| {
e.prevent_default();
};
view! {
main(class="container") {
form(on:submit=submit_fn) {
button(type="submit") {
"Submit"
}
}
}
}
```
Will cause error:
```rust
the trait bound `{closure@src/app.rs:41:21: 41:36}: EventHandler<_, submit, _>` is not satisfied
the trait `EventHandler<_, submit, _>` is not implemented for closure `{closure@src/app.rs:41:21: 41:36}`rustc[...](...)
app.rs(45, 5): required by a bound introduced by this call
generic_node.rs(128, 12): required by a bound in `event`
```
Defining function with empty closure `let submit_fn = move|_| {...}` infers to `impl Fn(SubmitEvent)` but you can't call …
=> Add 'SubmitEvent' to re-exported events from web_sys crate

examples/http-request-builder/src/main.rs, examples/http-request/src/main.rs
Replaced CountAPI as it got bought out then taken down by APILayer, this is a fully compliant replacement for it. 
This code was created in https://github.com/sycamore-rs/sycamore/pull/305
=> Replace CountAPI as it got taken down. 

packages/sycamore-macro/src/view.rs
The suggested change in #676 
The change would suppress the unwanted warning from rust-analyzer.
Note: clippy seems to have been failing for at least 3 weeks.
https://github.com/sycamore-rs/sycamore/actions/workflows/test.yml
=> Rename the tag type alias

packages/sycamore-web/src/elements.rs, packages/sycamore-web/src/node/dom.rs, packages/sycamore-web/src/node/hydrate.rs, packages/sycamore-web/src/node/mod.rs, packages/sycamore-web/src/node/ssr.rs
This change allows setting non `&'static str` values as attribute names, such as when programmatically building up the view tree from serialized data.
=> Make `ViewHtmlNode` methods use `Cow<'static, str>` instead of `&'static str`

packages/sycamore-web/src/components.rs
`NoHydrate` should render on the client side if we are not currently hydrating.
The current behavior should be superseded by server components (i.e. components that only run on the server)
=> Fix `NoHydrate` should render if not hydrating

packages/sycamore-router-macro/Cargo.toml, packages/sycamore-router-macro/src/parser.rs, packages/sycamore-router-macro/src/route.rs, packages/sycamore-router-macro/tests/router/router-fail.rs, packages/sycamore-router-macro/tests/router/router-fail.stderr
This PR removes a few dependencies from `sycamore-router-macro` which should improve compile times.
=> Remove `nom` dependency and replace with hand written parser

packages/sycamore-web/Cargo.toml, packages/sycamore-web/src/iter.rs, packages/sycamore-web/src/lib.rs, packages/sycamore-web/src/node/dom_node.rs, packages/sycamore-web/src/node/ssr_render.rs, packages/sycamore-web/src/portal.rs, packages/sycamore-web/src/suspense.rs, packages/sycamore-web/src/utils.rs
There was a subtle bug introduced in #679 regarding suspense support:
```rust
view! {
Suspense(fallback=view! { "Loading..." }) {
"Test"
AsyncComponent()
}
}
```
Would render the text `"TestLoading..."`.
This is because we don't support dynamically updating views when they are detached from the DOM. This used to fail silently but now will trigger a warning in the console.
This PR fixes this issue by first rendering the async view into a document fragment and then appending that document fragment when suspense is resolved.
=> Fix suspense rendering async shell during fallback

packages/sycamore-router/src/router.rs
Fixes a bug where navigating to a different pathname with a different hash triggers a browser refresh.
Instead, the router should intercept this and handle the navigation.
=> Fix router on different pathname and hash triggers hard refresh

website/index.html
Umami is a privacy focused open source analytics library.
Right now, we have no analytics whatsoever and I don't want to use Google Analytics.
=> Add umami analytics to website

.github/workflows/build_website.yml, .github/workflows/continuous_bench.yml, .github/workflows/coverage.yml, .github/workflows/fmt.yml, .github/workflows/js_framework_bench.yml, .github/workflows/post_js_framework_bench.yml, .github/workflows/test.yml, CONTRIBUTING.md, README.md, docs/next/getting_started/faq.md, docs/next/getting_started/installation.md, docs/src/main.rs, packages/tools/bench-diff/src/main.rs
Updates workflows and documentation by replacing instances of `master` with `main`.
=> Update branch name from `master` to `main`

docs/next/basics/view.md, packages/sycamore-macro/src/view.rs, packages/sycamore-macro/tests/view/element-pass.rs, packages/sycamore-view-parser/src/ir.rs, packages/sycamore-view-parser/src/parse.rs
Added a new PropType variant and the corresponding updates to parsing and dom manipulation. 
Added 1 case into 'element-pass' test using such quoted-string attribute.
Updated docs to show usage of "quoted string-literal" attribute name.
Note, that the issue #703 says _"Allow arbitrary attribute names by using string literal."_, but we are using [web_sys::Element::set_attribute](https://github.com/sycamore-rs/sycamore/blob/b6577326590257fef8268184d547ecce840b3d2a/packages/sycamore-web/src/node/dom_node.rs#L119), and that call will panic if you try to set attribute name to something illegal. It seems to get upset by anything except alphanumeric characters, underscores or non-leading-dashes.
But at least now you can add such horrible, but valid attributes, if needed:
```rust …
```
=> Allow attribute names by using string literal

examples/js-framework-benchmark/Cargo.toml, examples/todomvc/Cargo.toml, examples/todomvc/src/main.rs, packages/sycamore-reactive/src/maybe_dyn.rs, packages/sycamore-web/src/events.rs, packages/sycamore-web/src/lib.rs
Somehow they got removed at some point (probably during #679)
=> Add re-exports back to `sycamore-web`

examples/hello-builder/Cargo.toml, examples/hello-builder/src/main.rs, examples/http-request-builder/Cargo.toml, examples/http-request-builder/src/main.rs, examples/http-request/Cargo.toml, examples/http-request/src/main.rs, examples/hydrate/Cargo.toml, examples/hydrate/src/main.rs, examples/todomvc/Cargo.toml, examples/todomvc/src/main.rs, examples/transitions/Cargo.toml, examples/transitions/src/main.rs, website/Cargo.toml, website/src/header.rs, website/src/main.rs
Removes usage of `log`, `console_log`, and some other dependencies from examples that are no longer needed.
=> Cleanup some example dependencies

examples/attributes-passthrough/src/main.rs, packages/sycamore-macro/src/view.rs
Fix for #704.
The following expressions will be considered as non-dynamic (NDY):
- literal
- closure
- path
- field accessor
```rust
document.author.id
```
- parentheses, where inner expression is NDY
```rust
(expr)
```
- tuple, where elements are NDY
```rust
(a, b, c)
```
- array, where elements or length are NDY
```rust
[a, b, c]
[d; len]
```
- struct, where field values are NDY
```rust
Doc {
id: a,
author: Author {
id: (b, c),
},
}
```
- type cast, where expression is NDY
```rust
expr as sometype
```
- **view!** macro
- block, when either a const block, or all statements are NDY
- **loop**, **while** and **for**, (when all their parts are NDY)
- **break**, **continue**
- **let**, when pattern and expression are NDY
- **match**, when the matched expression, and all arms (patterns, …
=> Fix #704 - Updating the check whether a view must be dynamic.

packages/sycamore-reactive/src/maybe_dyn.rs, packages/sycamore/tests/web/cleanup.rs, packages/sycamore/tests/web/indexed.rs, packages/sycamore/tests/web/keyed.rs, packages/tools/bench/benches/reactivity.rs
This lays the foundation for supporting optional attributes in #622.
This is technically a breaking change because of some obscure type-inference changes. However, this should affect almost nobody.
=> Support `MaybeDyn<Option<Cow<'static, str>>>` and make some impls more flexible

packages/sycamore-reactive/Cargo.toml, packages/sycamore-reactive/src/root.rs, packages/sycamore/Cargo.toml
This was mostly used for debugging sycamore itself but is no longer needed.
=> Remove `tracing` from `sycamore-web`

packages/sycamore-web/src/node/dom_node.rs, packages/sycamore-web/src/node/ssr_node.rs, packages/sycamore-web/src/suspense.rs
Previous behavior: dynamic nodes created on the server were not actually dynamic, i.e. the values would not update even when signals are updated.
New behavior: dynamic nodes are always dynamic. This solves a bunch of inconsistencies and makes it easier to use resources which update the value dynamically.
=> Make `SsrNode` automatically create reactive nodes by default

packages/sycamore-reactive/src/utils.rs
Previous behavior tracked dependencies in both dependency list and in callback.
The expected behavior is probably that it only tracks the dependencies specified explicitly in the dependency list. This PR updates the `on` function to this behavior. Also adds a test to prevent regressions.
=> Do not track callback in `on` function callback

packages/sycamore-reactive/src/iter.rs, packages/sycamore-reactive/src/utils.rs
=> Fix do not track nested reactivity in `map_keyed`/`map_indexed`

packages/sycamore-macro/src/component.rs, packages/sycamore-macro/src/inline_props.rs, packages/sycamore-macro/tests/component/inline-props-pass.rs
Fixes a regression from `0.9.0-beta.4` where function arguments no longer forward their attributes to the generated prop struct when using `inline_props`.
For example, this should forward the attributes onto the corresponding field in the props struct.
```rust
#[component(inline_props)]
fn Foo(
/// Test
#[prop(default)]
value: i32,
) -> View { ... }
```
=> Forward attributes on function parameters to generated prop struct in `inline_props`

README.md
I just realized that the old README.md had some quite outdated information around. This updates the `README.md`
=> Update README.md with new details

packages/sycamore-router/src/router.rs
Simplify the implementations of the `navigate`, `navigate_replace`, and `navigate_no_history` functions by sharing more code.
=> Simplify navigate functions in router

packages/sycamore-macro/src/lib.rs, packages/sycamore-view-parser/src/codegen.rs, packages/sycamore-view-parser/src/lib.rs
This would greatly simplify making 3rd party alternative view macros #23 only having to make the common ir rather then a custom solution that would work basically identically to the existing codegen solution.
Right now the view.rs was not accessible by other crates because the crate it is in is a proc-macro crate.
I know that technically the crate is named sycamore-view-**parser** and codegen isn't parsing but making a separate crate would be redundant in my opinion since the ir is also needed together with the codegen and i don't think its worth it renaming the crate since its already on crates.io.
Unrelated side note: I am working on and off on Fallible components trying to make it good. I just need a short change (e.g. making sycamore-rstml)
=> Move view.rs from sycamore-macro into sycamore-view-parser codegen.rs

docs/next/introduction/your-first-app.md
Compiler was complaining about this. Apparently we need .into() or .to_string(). Feel free to change this to whatever is preferred.
In a previous Sycamore version, was this not required?
=> owned String required .into() or .to_string()

docs/next/introduction/adding-state.md
Sorry for the PR spam, just going through the tutorial :)
=> signal instead of value name of var

packages/sycamore-view-parser/src/codegen.rs
=> Fix view update handling for dynamic field bases

packages/sycamore-reactive/src/context.rs, packages/sycamore-reactive/src/node.rs
=> Fix context not removed when node is rerun

docs/next/introduction/adding-state.md
I was referring to this part of the docs multiple times and each time I was puzzled, should I de-reference here or not.
Rust says I should.
Hope this will solve a confusion for future users.
=> Fix missing deref in adding-state.md example

docs/next/router.md
This PR modifies the existing docs to better reflect the example provided in:
[/examples/router/src/main.rs](https://github.com/sycamore-rs/sycamore/blob/main/examples/router/src/main.rs)
I tried to follow the previous documentation and ran into trait bound errors with Copy. I found the example and managed to get it working. Figured that I would propose changing the docs to reflect that example better.
=> Update router documentation

packages/sycamore/src/motion.rs
We were simply accessing the callback but not actually calling it. Silly me!
Fixes #790
=> Fix bug where the stop function in `create_raf_loop` was not actually being called

.github/workflows/test.yml, packages/sycamore/Cargo.toml
On the branch to be merged, Cargo provides a helpful error message if you try to build a Sycamore app with a Rust toolchain below the minimum supported version. This is accomplished by setting [`rust-version`](https://doc.rust-lang.org/cargo/reference/rust-version.html) in the package description.
The new `msrv` job in the `test` workflow builds the `web` integration test on a Rust toolchain below the minimum supported version, and confirms that Cargo prints the expected error message. The Rust toolchain-version is hard-coded, and has to be updated by hand when the MSRV changes.
Updates to the MSRV will have to be reflected by hand in three places:
- The "Your First App" documentation page.
- On the main branch, this is the only place that reflects the MSRV.
- The `rust-version` setting …
=> Enforce minimum supported Rust version

docs/next/troubleshooting.md, examples/ssr-streaming/src/main.rs, packages/sycamore-web/src/lib.rs, packages/sycamore-web/src/node/mod.rs
This is a better fix to #792 
Also deprecates `cfg_ssr_item!` and `cfg_not_ssr_item!` since they can just be replaced by `is_ssr!` and `is_not_ssr!`.
=> Reimplement `is_ssr!` and `is_not_ssr!` macros to not trigger unknown cfg warning

packages/sycamore-macro/src/lib.rs, packages/sycamore-web/src/lib.rs
=> Fix `#[cfg_ssr]` and `#[cfg_not_ssr]` to use `is_ssr!` and `is_not_ssr!` macros.
