maple-core/src/reactive.rs

This PR changes `create_memo` to internally use `create_signal`.

Fix dependencies on create_memo

---

.github/workflows/test.yml
Cargo.toml
examples/tweened/Cargo.toml
examples/tweened/index.html
examples/tweened/src/main.rs
maple-core/Cargo.toml
maple-core/src/easing.rs
maple-core/src/lib.rs
maple-core/src/reactive.rs
maple-core/src/reactive/effect.rs
maple-core/src/reactive/motion.rs
maple-core/src/reactive/signal.rs
maple-core/src/utils.rs

Tweened Values

---

docs/Cargo.toml
docs/index.scss
docs/markdown/basics/data_binding.md
docs/src/content.rs
docs/src/sidebar.rs
examples/hello/Cargo.toml
examples/hello/src/main.rs
examples/ssr/Cargo.toml
examples/todomvc/Cargo.toml
examples/todomvc/src/header.rs
maple-core-macro/src/template/attributes.rs
maple-core-macro/src/template/element.rs
maple-core/Cargo.toml
maple-core/src/generic_node.rs
maple-core/src/generic_node/dom_node.rs
maple-core/src/generic_node/ssr_node.rs
maple-core/src/lib.rs
maple-core/tests/integration/main.rs

2-way data binding

---

maple-core/src/reactive/effect.rs

address issue #71

---

.github/workflows/js_framework_bench.yml
packages/sycamore-macro/src/template/attributes.rs
packages/sycamore-macro/src/template/text.rs
packages/sycamore/Cargo.toml
packages/sycamore/benches/reactivity.rs
packages/sycamore/src/flow.rs
packages/sycamore/src/generic_node/dom_node.rs
packages/sycamore/src/lib.rs
packages/sycamore/src/rx/iter.rs
packages/sycamore/tests/web/keyed.rs
packages/sycamore/tests/web/main.rs

- Intern strings in `DomNode::element`
- Intern attribute name in `DomNode::set_attribute`
- Intern static literals in `sycamore-macro`

Various performance improvements

---

docs/markdown/advanced/routing.md
docs/markdown/advanced/ssr.md
docs/src/content.rs
packages/sycamore-macro/src/template/attributes.rs
packages/sycamore-router-macro/src/lib.rs
packages/sycamore-router/src/lib.rs
packages/sycamore-router/src/router.rs
packages/sycamore/src/component.rs
packages/sycamore/src/generic_node.rs
packages/sycamore/src/generic_node/dom_node.rs
packages/sycamore/src/generic_node/render.rs
packages/sycamore/src/generic_node/ssr_node.rs
packages/sycamore/src/rx/iter.rs

Documentation for Router + SSR

---

packages/sycamore/src/rx/iter.rs
packages/sycamore/tests/web/keyed.rs
packages/sycamore/tests/web/non_keyed.rs

Do not panic when map_keyed is updated with same data

---

docs/Cargo.toml
docs/build.rs
docs/next/advanced/routing.md
docs/next/getting_started/installation.md
docs/syntax/TOML.sublime-syntax
docs/versioned_docs/v0.5/getting_started/installation.md
packages/sycamore-router-macro/src/lib.rs
packages/sycamore-router-macro/src/parser.rs
packages/sycamore-router-macro/src/route.rs
packages/sycamore-router-macro/tests/router/router-fail.rs
packages/sycamore-router-macro/tests/router/router-fail.stderr
packages/sycamore-router-macro/tests/router/router-pass.rs
packages/sycamore-router/Cargo.toml
packages/sycamore-router/src/lib.rs
packages/sycamore-router/src/router.rs
website/index.css
website/index.html
website/src/content.rs
website/src/main.rs

Router preload

---

packages/sycamore-router/src/router.rs

Added scroll to top when we navigate

---

.github/workflows/build_website.yml
.github/workflows/build_website_prod.yml
.gitpod.Dockerfile
packages/sycamore/src/context.rs
packages/sycamore/src/lib.rs
packages/sycamore/src/portal.rs
packages/sycamore/src/template.rs
packages/sycamore/tests/web/cleanup.rs
packages/sycamore/tests/web/main.rs
packages/sycamore/tests/web/portal.rs
website/index.html
website/src/content.rs
website/src/index.rs
website/src/news_index.rs
website/src/versions.rs

Implement Portals

---

packages/sycamore-reactive/src/iter.rs

Use more rust idioms in map_indexed and map_keyed

---

packages/sycamore/src/generic_node/ssr_node.rs
packages/sycamore/tests/ssr/main.rs

Use push_str on &mut String directly

---

.github/workflows/build_website.yml
.github/workflows/build_website_prod.yml
examples/context/index.html
netlify.toml
packages/sycamore/src/context.rs
packages/sycamore/src/motion.rs
website/src/versions.rs

Build rustdoc in CI

---

packages/sycamore-reactive/src/signal.rs

This is for the same reasons as #257. I also removed the static lifetime, I'm not sure what I was thinking when I added it...

impl Default for StateHandle<T: Default>

---

.github/workflows/coverage.yml
packages/sycamore/src/context.rs
packages/sycamore/src/easing.rs
packages/sycamore/src/generic_node/ssr_node.rs
packages/sycamore/src/noderef.rs

Collect code coverage in CI

---

docs/next/basics/iteration.md

Fix example code in iteration docs

---

.gitignore
examples/hydrate/src/main.rs
packages/sycamore/Cargo.toml
packages/sycamore/src/builder/agnostic/mod.rs
packages/sycamore/src/generic_node/ssr_node.rs
packages/sycamore/src/utils/hydrate/mod.rs

Make output of `render_to_string` fixed

---

LICENSE

Update license for 2022

---

packages/sycamore-router/src/lib.rs
packages/sycamore-router/src/router.rs

Simplify certain parts of the sycamore-router crate and fix some error messages using old terminology

Router refactor

---

packages/sycamore-macro/tests/view/component-pass.rs
packages/sycamore-reactive/Cargo.toml
packages/sycamore-reactive/src/arena.rs
packages/sycamore-reactive/src/effect.rs
packages/sycamore-reactive/src/lib.rs

Use bumpalo instead of hand-rolled arena implementation

---

packages/sycamore-web/src/lib.rs

_if someone wants to contribute a doctest for this function, that will be very welcome!_
I should have probably have added it in the initial PR tbh :)

Add doc test example for `from_web_sys`

---

packages/sycamore-reactive/src/iter.rs
packages/sycamore/src/flow.rs

Relax restriction on `T` in `Keyed` from `Eq` to `PartialEq`

---

packages/sycamore-router/src/router.rs

Fix hydration with `Router` and `StaticRouter`

---

README.md

Call me crazy but I think this looks better

Centered badges

---

packages/sycamore-router/src/lib.rs

fixes #562.
It's a simple problem with many possible solutions, I've decided to go with using the heap, it is possible to only use slices but the code becomes less readable.
Let me know if you've got a better idea.

Fix #562 / ignore the query parameters when matching a path to a route

---

.github/workflows/test.yml
docs/next/getting_started/installation.md
packages/sycamore-core/src/generic_node.rs
packages/sycamore-macro/tests/component/inline-props-fail.stderr
packages/sycamore-macro/tests/view/component-fail.stderr
packages/sycamore-macro/tests/view/element-fail.stderr
packages/tools/bench-diff/src/main.rs

Fixes broken CI
Also updates NodeJS version in CI to `18.x`

Update MSRV to 1.72

---

docs/next/basics/components.md

Update the components documentation to reflect the latest changes in Sycamore v0.9.

Update components documentation for v0.9

---

website/Cargo.toml
website/src/content.rs
website/src/header.rs
website/src/main.rs
website/src/sidebar.rs

#619
I implemented only "(A) highlight current page in navbar"

Add underline and bold for navigation improvements

---

docs/next/basics/view.md
docs/next/getting_started/hello_world.md

Updated section on builder API. This was not updated as part of #679.

Update some old docs

---

packages/sycamore-reactive/src/signals.rs

Trivial fix to a small typo
Closes #672

Fix `set_fn` to not be silent

---

packages/sycamore-futures/src/suspense.rs

This prevents a scenario where a nested `Suspense` component creates a suspense context inside a nested scope that cannot be accessed from outside.

Fix suspense should create context in global scope

---

docs/next/getting_started/faq.md

https://survey.stackoverflow.co/2023/#section-admired-and-desired-programming-scripting-and-markup-languages

Update faq.md, rust is the 2023-most-desired-language

---

netlify.toml
website/src/content.rs
website/src/header.rs
website/src/main.rs
website/src/news_index.rs
website/src/versions.rs

This PR adds a banner to the old website telling users to visit the new website. Also changes a bunch of links.

Update old website to migrate to sycamore.dev

---

netlify.toml

Maybe this will fix Netlify's redirect?

Force redirect home page to new website

---

.github/workflows/build_examples.yml

Follow-up to #730. Hopefully this works.

Fix build example workflow again

---

examples/attributes-passthrough/src/main.rs
examples/components/src/main.rs
examples/context/src/main.rs
examples/counter/src/main.rs
examples/hello-builder/src/main.rs
examples/hydrate/src/main.rs
examples/js-framework-benchmark/src/main.rs
examples/js-snippets/src/main.rs
examples/motion/src/main.rs
examples/ssr-streaming/src/app.rs
examples/ssr/src/main.rs
examples/timer/src/main.rs
examples/todomvc/src/main.rs
packages/sycamore-web/src/view.rs

This lets us write:
```rust
let signal = create_signal(123);
view! {
(signal) // Previously, `(signal.get())`
}
```

Implement `Into<View>` for signal like types

---

packages/sycamore-web/src/node/ssr_render.rs

Fix broken expect test

---

packages/sycamore-reactive/src/signals.rs

Replaces the panic message with one that is slightly more helpful.

Slightly better error messages for read/updating a signal while updating/reading

---

packages/sycamore-macro/src/component.rs
packages/sycamore-macro/src/inline_props.rs
packages/sycamore-macro/src/lib.rs
packages/sycamore-macro/tests/component/inline-props-fail.rs
packages/sycamore-macro/tests/component/inline-props-fail.stderr
packages/sycamore-macro/tests/component/inline-props-pass.rs
packages/sycamore-macro/tests/ui.rs

Support `impl Trait` syntax with `inline_props`

---

Cargo.toml
examples/README.md
examples/hello-world/index.html
examples/router/Cargo.toml
examples/router/index.html
examples/router/src/main.rs

I was going to tackle the remaining 0.9 issues, half of which are router related, and i noticed that there is no example using router (which would be useful for router development).

Router example

---

packages/sycamore-macro/src/component.rs
packages/sycamore-macro/tests/component/inline-props-pass.rs

Allow adding derives to generated prop type for `inline_props`

---

packages/sycamore-router/src/router.rs

Router refresh

---

.github/workflows/build_examples.yml
.github/workflows/js_framework_bench.yml

Accidentally messed up git history with previous PR.

Update trunk to v0.21.1 in GitHub Actions workflows

---

packages/sycamore-futures/src/suspense.rs
packages/sycamore-macro/src/props.rs
packages/sycamore-reactive/src/effects.rs
packages/sycamore-reactive/src/maybe_dyn.rs
packages/sycamore-reactive/src/memos.rs
packages/sycamore-reactive/src/node.rs
packages/sycamore-reactive/src/root.rs
packages/sycamore-reactive/src/signals.rs
packages/sycamore-router/src/lib.rs
packages/sycamore-router/src/router.rs
packages/sycamore-web/src/attributes.rs
packages/sycamore-web/src/events.rs
packages/sycamore-web/src/iter.rs
packages/sycamore-web/src/resource.rs
packages/sycamore-web/src/stable_counter.rs
packages/sycamore-web/src/suspense.rs
packages/sycamore-web/src/utils.rs
packages/sycamore/src/lib.rs

Fix some typos

---

docs/next/introduction/your-first-app.md

head should be html

---

docs/next/introduction/rendering-lists.md

Fix: spelling mistake in code example

Fix typo in rendering-lists.md

---

LICENSE

Haven't done this in a while...

Update LICENSE year to 2025
